// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20231102220410_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Auth.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorFirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AuthorLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Author", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AuthorFirstMidName = "Douglas",
                            AuthorLastName = "Adams"
                        },
                        new
                        {
                            AuthorId = 2,
                            AuthorFirstMidName = "Suzanne",
                            AuthorLastName = "Collins"
                        },
                        new
                        {
                            AuthorId = 3,
                            AuthorFirstMidName = "Dan",
                            AuthorLastName = "Brown"
                        },
                        new
                        {
                            AuthorId = 4,
                            AuthorFirstMidName = "Joanne",
                            AuthorLastName = "Rowling"
                        },
                        new
                        {
                            AuthorId = 5,
                            AuthorFirstMidName = "Jerome David",
                            AuthorLastName = "Salinger"
                        },
                        new
                        {
                            AuthorId = 6,
                            AuthorFirstMidName = "Harper",
                            AuthorLastName = "Lee"
                        },
                        new
                        {
                            AuthorId = 7,
                            AuthorFirstMidName = "John",
                            AuthorLastName = "Tolkien"
                        },
                        new
                        {
                            AuthorId = 8,
                            AuthorFirstMidName = "George",
                            AuthorLastName = "Orwell"
                        },
                        new
                        {
                            AuthorId = 9,
                            AuthorFirstMidName = "Khaled",
                            AuthorLastName = "Hosseini"
                        },
                        new
                        {
                            AuthorId = 10,
                            AuthorFirstMidName = "Stieg",
                            AuthorLastName = "Larsson"
                        });
                });

            modelBuilder.Entity("Core.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("BookAuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BookReturnDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("BookTakeDate")
                        .HasColumnType("date");

                    b.HasKey("BookId");

                    b.HasIndex("BookAuthorId");

                    b.HasIndex("BookISBN")
                        .IsUnique();

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookAuthorId = 1,
                            BookDescription = "A hilarious science fiction comedy that follows the adventures of Arthur Dent, a hapless human who escapes the destruction of Earth with the help of an alien friend. The book is full of witty humor, absurd situations, and clever references to various aspects of culture and science.",
                            BookISBN = "9780330258641",
                            BookName = "The Hitchhiker’s Guide to the Galaxy"
                        },
                        new
                        {
                            BookId = 2,
                            BookAuthorId = 2,
                            BookDescription = "A dystopian novel that depicts a brutal reality show where 24 teenagers are forced to fight to the death in a televised arena. The book explores themes of survival, rebellion, and morality through the perspective of Katniss Everdeen, a 16-year-old girl who volunteers to take her sister’s place in the deadly game.",
                            BookISBN = "9780439023528",
                            BookName = "The Hunger Games"
                        },
                        new
                        {
                            BookId = 3,
                            BookAuthorId = 3,
                            BookDescription = "A thriller that revolves around a murder mystery involving a secret society, a religious conspiracy, and a hidden code in Leonardo da Vinci’s paintings. The book is full of suspense, puzzles, and historical facts that challenge the reader’s knowledge and beliefs.",
                            BookISBN = "978030745454",
                            BookName = "The Da Vinci Code"
                        },
                        new
                        {
                            BookId = 4,
                            BookAuthorId = 4,
                            BookDescription = "A fantasy novel that introduces the magical world of Harry Potter, a young boy who discovers that he is a wizard and attends Hogwarts School of Witchcraft and Wizardry. The book is full of imagination, adventure, and friendship as Harry learns to master his powers and faces his nemesis, Lord Voldemort.",
                            BookISBN = "9780141950432",
                            BookName = "Harry Potter and the Philosopher’s Stone"
                        },
                        new
                        {
                            BookId = 5,
                            BookAuthorId = 5,
                            BookDescription = "A classic novel that portrays the alienation and disillusionment of Holden Caulfield, a 17-year-old boy who runs away from his boarding school and wanders around New York City. The book captures the voice and emotions of a troubled teenager who struggles to find meaning and identity in a phony world.",
                            BookISBN = "9791456789012",
                            BookName = "The Catcher in the Rye"
                        },
                        new
                        {
                            BookId = 6,
                            BookAuthorId = 6,
                            BookDescription = "A Pulitzer Prize-winning novel that depicts the racial injustice and social inequality in the American South during the 1930s. The book is narrated by Scout Finch, a 6-year-old girl who witnesses her father, Atticus Finch, defend a black man accused of raping a white woman in a court trial.",
                            BookISBN = "9780060935467",
                            BookName = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 7,
                            BookAuthorId = 7,
                            BookDescription = "An epic fantasy novel that tells the story of Frodo Baggins, a hobbit who inherits a powerful ring from his uncle Bilbo Baggins and embarks on a quest to destroy it in the fires of Mount Doom. The book is set in Middle-earth, a richly detailed world full of elves, dwarves, orcs, and other mythical creatures.",
                            BookISBN = "9790345678904",
                            BookName = "The Lord of the Rings"
                        },
                        new
                        {
                            BookId = 8,
                            BookAuthorId = 8,
                            BookDescription = "A dystopian novel that depicts a totalitarian society where Big Brother, the leader of the Party, controls every aspect of life through propaganda, surveillance, and censorship. The book follows Winston Smith, a low-ranking member of the Party who secretly rebels against the system by writing a diary and falling in love with Julia.",
                            BookISBN = "9781234567897",
                            BookName = "Nineteen Eighty-Four "
                        },
                        new
                        {
                            BookId = 9,
                            BookAuthorId = 9,
                            BookDescription = "A historical fiction novel that traces the friendship and betrayal of Amir and Hassan, two boys from different social classes in Afghanistan. The book spans over three decades of war, violence, and migration as Amir tries to redeem himself for his past sins.",
                            BookISBN = "9780123456789",
                            BookName = "The Kite Runner"
                        },
                        new
                        {
                            BookId = 10,
                            BookAuthorId = 10,
                            BookDescription = "A crime novel that involves the investigation of a 40-year-old disappearance case by Mikael Blomkvist, a journalist, and Lisbeth Salander, a hacker with a troubled past. The book is full of twists, turns, and secrets that expose the dark side of Swedish society.",
                            BookISBN = "9781594631931",
                            BookName = "The Girl with the Dragon Tattoo"
                        });
                });

            modelBuilder.Entity("Core.Models.BookGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "BookId");

                    b.HasIndex("BookId");

                    b.HasIndex("GenreId", "BookId");

                    b.ToTable("BookGenre", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            BookId = 1
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 2
                        },
                        new
                        {
                            GenreId = 9,
                            BookId = 2
                        },
                        new
                        {
                            GenreId = 3,
                            BookId = 3
                        },
                        new
                        {
                            GenreId = 5,
                            BookId = 4
                        },
                        new
                        {
                            GenreId = 8,
                            BookId = 5
                        },
                        new
                        {
                            GenreId = 6,
                            BookId = 5
                        },
                        new
                        {
                            GenreId = 7,
                            BookId = 5
                        },
                        new
                        {
                            GenreId = 8,
                            BookId = 6
                        },
                        new
                        {
                            GenreId = 12,
                            BookId = 6
                        },
                        new
                        {
                            GenreId = 5,
                            BookId = 7
                        },
                        new
                        {
                            GenreId = 12,
                            BookId = 9
                        },
                        new
                        {
                            GenreId = 9,
                            BookId = 8
                        },
                        new
                        {
                            GenreId = 10,
                            BookId = 8
                        },
                        new
                        {
                            GenreId = 11,
                            BookId = 8
                        },
                        new
                        {
                            GenreId = 4,
                            BookId = 10
                        },
                        new
                        {
                            GenreId = 3,
                            BookId = 10
                        });
                });

            modelBuilder.Entity("Core.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Science fiction"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Thriller"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Detective novel"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Realism"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Satire"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "Bildungsroman"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "Dystopian"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 11,
                            GenreName = "Political fiction"
                        },
                        new
                        {
                            GenreId = 12,
                            GenreName = "Social novel"
                        },
                        new
                        {
                            GenreId = 13,
                            GenreName = "Southern Gothic"
                        },
                        new
                        {
                            GenreId = 14,
                            GenreName = "Historical fiction"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Models.Book", b =>
                {
                    b.HasOne("Core.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("BookAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Core.Models.BookGenre", b =>
                {
                    b.HasOne("Core.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Core.Models.Book", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("Core.Models.Genre", b =>
                {
                    b.Navigation("BookGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
